# streamlit/Dockerfile.celery
FROM python:3.10

# Create and set the working directory
RUN mkdir /app
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the entire app
COPY . .

# Set PYTHONPATH to include both /app and /app/ligify
ENV PYTHONPATH=/app:/app/ligify
